import Head from "next/head";
import { Inter } from "next/font/google";
import styles from './Home.module.css';


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Spiral-Practical</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://spiraltechnolabs.com/wp-content/uploads/2023/04/cropped-final-logo-footer-optimized.png" />
      </Head>
      <div className={styles.container}>
      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Spiral Technolabs</h1>
        <p className={styles.description}>
          This is a simple home page created with Next.js.
        </p>
      </main>
    </div>
    </>
  );
}
